branches:
  - name: main
    prerelease: rc

tagFormat: 'v${version}'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/exec'